HospitalProjectDemo/HospitalProject/Controllers/ConsultationController.cs
using HospitalProject.Models;
using HospitalProject.Repositories.Consultation;
using HospitalProject.Repositories.RoomsRegisters;
using HospitalProject.Services.Email;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HospitalProject.Controllers
{
    public class ConsultationController : Controller
    {
        private readonly IConsultationsRepository _consultationsRepository;
        private readonly IEmailService _emailService;
        private SelectList _patientList;
        private SelectList _doctorList;
        private SelectList _medicinesList;

        public ConsultationController(IConsultationsRepository consultationsRepository, IEmailService emailService)
        {
            _consultationsRepository = consultationsRepository;
            _emailService = emailService;

            _patientList = new SelectList(_consultationsRepository.GetAllPatients(),
                      nameof(PatientsModel.PacienteID),
                      nameof(PatientsModel.NombreCompleto));

            _doctorList = new SelectList(_consultationsRepository.GetAllDoctors(),
                      nameof(DoctorsModel.DoctorID),
                      nameof(DoctorsModel.NombreCompleto));

            _medicinesList = new SelectList(_consultationsRepository.GetAllMedicines(),
                      nameof(MedicinesModel.MedicamentoID),
                      nameof(MedicinesModel.Nombre));
        }

        public ActionResult Index()
        {
            return View(_consultationsRepository.GetAll());
        }

        // GET: UniverstiyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UniverstiyController/Create
        public ActionResult Create()
        {
            ViewBag.Patients = _patientList;
            ViewBag.Doctors = _doctorList;
            ViewBag.Medicines = _medicinesList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ConsultationModel consultationModel)
        {
            try
            {
                _consultationsRepository.AddConsultations(consultationModel);

                TempData["message"] = "Datos guardados exitosamente";

                string email = "hospital@gmail.com";
                string subject = "Resultado de Consulta";
                string body = "Resultado de Consulta jajajajja";

                _emailService.SendEmail(email, "Williams", subject, body);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Patients = _patientList;
                ViewBag.Doctors = _doctorList;
                ViewBag.Medicines = _medicinesList;

                return View(consultationModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var consultation = _consultationsRepository.GetById(id);

            _patientList = new SelectList(_consultationsRepository.GetAllPatients(),
                                        nameof(PatientsModel.PacienteID),
                                        nameof(PatientsModel.NombreCompleto),
                                        consultation?.Pacientes?.PacienteID);

            _doctorList = new SelectList(_consultationsRepository.GetAllDoctors(),
                                        nameof(DoctorsModel.DoctorID),
                                        nameof(DoctorsModel.NombreCompleto),
                                        consultation?.Doctores?.DoctorID);

            _medicinesList = new SelectList(_consultationsRepository.GetAllMedicines(),
                            nameof(MedicinesModel.MedicamentoID),
                            nameof(MedicinesModel.Nombre),
                            consultation?.Medicinas?.MedicamentoID);

            ViewBag.Patients = _patientList;
            ViewBag.Doctors = _doctorList;
            ViewBag.Medicines = _medicinesList;

            if (consultation == null)
            {
                return NotFound();
            }

            return View(consultation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ConsultationModel consultationModel)
        {
            try
            {
                _consultationsRepository.EditConsultations(consultationModel);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Patients = _patientList;
                ViewBag.Doctors = _doctorList;
                ViewBag.Medicines = _medicinesList;

                return View(consultationModel);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var consultation = _consultationsRepository.GetById(id);

            if (consultation == null)
            {
                return NotFound();
            }

            var pacient = _consultationsRepository.GetAllPatients();
            var doctors = _consultationsRepository.GetAllDoctors();
            var medicines = _consultationsRepository.GetAllMedicines();

            consultation.Pacientes = pacient.FirstOrDefault(p => p.PacienteID == consultation.PacienteID);
            consultation.Doctores = doctors.FirstOrDefault(r => r.DoctorID == consultation.DoctorID);
            consultation.Medicinas = medicines.FirstOrDefault(p => p.MedicamentoID == consultation.PacienteID);

            return View(consultation);
        }

        // POST: UniverstiyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ConsultationModel consultationModel)
        {
            try
            {
                _consultationsRepository.DeleteConsultations(consultationModel.ConsultaID);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(consultationModel);
            }
        }
    }
}

HospitalProjectDemo/HospitalProject/Views/Consultation/Create.cshtml
@model HospitalProject.Models.ConsultationModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ConsultationModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaConsulta" class="control-label"></label>
                <input asp-for="FechaConsulta" class="form-control" />
                <span asp-validation-for="FechaConsulta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diagnostico" class="control-label"></label>
                <input asp-for="Diagnostico" class="form-control" />
                <span asp-validation-for="Diagnostico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PacienteID" class="control-label"></label>
                <select asp-for="PacienteID"
                        asp-items="@ViewBag.Patients"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="PacienteID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorID" class="control-label"></label>
                <select asp-for="DoctorID"
                        asp-items="@ViewBag.Doctors"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="DoctorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicamentoID" class="control-label"></label>
                <select asp-for="MedicamentoID"
                        asp-items="@ViewBag.Medicines"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="MedicamentoID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProjectDemo/HospitalProject/Views/Consultation/Delete.cshtml
@model HospitalProject.Models.ConsultationModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ConsultationModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConsultaID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConsultaID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaConsulta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaConsulta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diagnostico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diagnostico)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PacienteID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pacientes.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Doctores.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MedicamentoID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medicinas.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input asp-for="ConsultaID" hidden class="form-control" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HospitalProjectDemo/HospitalProject/Views/Consultation/Edit.cshtml
@model HospitalProject.Models.ConsultationModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ConsultationModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="ConsultaID" hidden class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="FechaConsulta" class="control-label"></label>
                <input asp-for="FechaConsulta" class="form-control" />
                <span asp-validation-for="FechaConsulta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diagnostico" class="control-label"></label>
                <input asp-for="Diagnostico" class="form-control" />
                <span asp-validation-for="Diagnostico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PacienteID" class="control-label"></label>
                <select asp-for="PacienteID"
                        asp-items="@ViewBag.Patients"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="PacienteID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorID" class="control-label"></label>
                <select asp-for="DoctorID"
                        asp-items="@ViewBag.Doctors"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="DoctorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicamentoID" class="control-label"></label>
                <select asp-for="MedicamentoID"
                        asp-items="@ViewBag.Medicines"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="MedicamentoID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProjectDemo/HospitalProject/Views/Consultation/Index.cshtml
@model IEnumerable<HospitalProject.Models.ConsultationModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@if (TempData["message"] != null)
{
    <div class="alert alert-primary" role="alert">
        @TempData["message"]
    </div>
}

<table class="table table-bordered table-striped table-responsive" id="consultationTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ConsultaID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaConsulta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diagnostico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PacienteID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MedicamentoID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ConsultaID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaConsulta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diagnostico)
            </td>
            <td>
                @item.Pacientes?.NombreCompleto
            </td>
            <td>
                @item.Doctores?.NombreCompleto
            </td>
            <td>
                @item.Medicinas?.Nombre
            </td>
            <td>
                <a asp-controller="Consultation" asp-action="Edit" asp-route-id="@item.ConsultaID" class="btn btn-primary">Editar</a>
                <a asp-controller="Consultation" asp-action="Delete" asp-route-id="@item.ConsultaID" class="btn btn-primary">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#consultationTable").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    }
                ],
                columnDefs: [
                    {
                        targets: 6,
                        orderable: false,
                        searchable: false
                    }
                ],
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/es-ES.json'
                }
            });
        });
    </script>
}