HospitalProjectDemo/HospitalProject/Controllers/DoctorSpecialtyController.cs
using HospitalProject.Models;
using HospitalProject.Repositories.DoctorSpecialty;
using Microsoft.AspNetCore.Mvc;

namespace HospitalProject.Controllers
{
    public class DoctorSpecialtyController : Controller
    {
        private readonly IDoctorSpecialtyRepository _doctorSpecialtyRepository;

        public DoctorSpecialtyController(IDoctorSpecialtyRepository doctorSpecialtyRepository)
        {
            _doctorSpecialtyRepository = doctorSpecialtyRepository;
        }

        public ActionResult Index()
        {
            return View(_doctorSpecialtyRepository.GetAll());
        }

        // GET: UniverstiyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UniverstiyController/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DoctorSpecialtyModel doctorSpecialtyModel)
        {
            try
            {
                _doctorSpecialtyRepository.AddDoctorSpecialty(doctorSpecialtyModel);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(doctorSpecialtyModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var doctorSpecialty = _doctorSpecialtyRepository.GetById(id);

            if (doctorSpecialty == null)
            {
                return NotFound();
            }

            return View(doctorSpecialty);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DoctorSpecialtyModel doctorSpecialtyModel)
        {
            try
            {
                _doctorSpecialtyRepository.EditDoctorSpecialty(doctorSpecialtyModel);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(doctorSpecialtyModel);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var doctorSpecialty = _doctorSpecialtyRepository.GetById(id);

            if (doctorSpecialty == null)
            {
                return NotFound();
            }

            return View(doctorSpecialty);
        }

        // POST: UniverstiyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(DoctorSpecialtyModel doctorSpecialtyModel)
        {
            try
            {
                _doctorSpecialtyRepository.DeleteDoctorSpecialty(doctorSpecialtyModel.EspecialidadID);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(doctorSpecialtyModel);
            }
        }
    }
}

HospitalProjectDemo/HospitalProject/Views/DoctorSpecialty/Create.cshtml
@model DoctorSpecialtyModel

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Nueva Especialidad</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreEspecialidad" class="control-label"></label>
                <input asp-for="NombreEspecialidad" class="form-control" />
                <span asp-validation-for="NombreEspecialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionEspecialidad" class="control-label"></label>
                <input asp-for="DescripcionEspecialidad" class="form-control" />
                <span asp-validation-for="DescripcionEspecialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProjectDemo/HospitalProject/Views/DoctorSpecialty/Delete.cshtml
@model DoctorSpecialtyModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DoctorSpecialtyModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EspecialidadID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EspecialidadID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreEspecialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreEspecialidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionEspecialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescripcionEspecialidad)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input asp-for="EspecialidadID" hidden class="form-control" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HospitalProjectDemo/HospitalProject/Views/DoctorSpecialty/Edit.cshtml
@model HospitalProject.Models.DoctorSpecialtyModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DoctorSpecialtyModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="EspecialidadID" hidden class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="NombreEspecialidad" class="control-label"></label>
                <input asp-for="NombreEspecialidad" class="form-control" />
                <span asp-validation-for="NombreEspecialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionEspecialidad" class="control-label"></label>
                <input asp-for="DescripcionEspecialidad" class="form-control" />
                <span asp-validation-for="DescripcionEspecialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProjectDemo/HospitalProject/Views/DoctorSpecialty/Index.cshtml
@model IEnumerable<HospitalProject.Models.DoctorSpecialtyModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-controller="DoctorSpecialty">Nueva Especialidad</a>
</p>

@if (TempData["message"] != null)
{
    <div class="alert alert-primary" role="alert">
        @TempData["message"]
    </div>
}

<table class="table table-bordered table-striped table-responsive" id="doctorSpecialtyTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EspecialidadID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreEspecialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescripcionEspecialidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EspecialidadID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreEspecialidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescripcionEspecialidad)
            </td>
            <td>
                <a asp-controller="DoctorSpecialty" asp-action="Edit" asp-route-id="@item.EspecialidadID" class="btn btn-primary">Editar</a>
                <a asp-controller="DoctorSpecialty" asp-action="Delete" asp-route-id="@item.EspecialidadID" class="btn btn-primary">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#doctorSpecialtyTable").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    }
                ],
                columnDefs: [
                    {
                        targets: 3,
                        orderable: false,
                        searchable: false
                    }
                ],
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/es-ES.json'
                }
            });
        });
    </script>
}