HospitalProjectDemo/HospitalProject/Controllers/RoomsRegisterController.cs
using HospitalProject.Models;
using HospitalProject.Repositories.Doctor;
using HospitalProject.Repositories.RoomsRegisters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HospitalProject.Controllers
{
    public class RoomsRegisterController : Controller
    {
        private readonly IRoomsRegistersRepository  _roomsRegistersRepository;
        private SelectList _roomsList;
        private SelectList _patientsList;

        public RoomsRegisterController(IRoomsRegistersRepository roomsRegistersRepository)
        {
            _roomsRegistersRepository = roomsRegistersRepository;

            _roomsList = new SelectList(_roomsRegistersRepository.GetAllRooms(),
                                  nameof(RoomsModel.HabitacionID),
                                  nameof(RoomsModel.NumeroHabitacion));

            _patientsList = new SelectList(_roomsRegistersRepository.GetAllPatients(),
                                  nameof(PatientsModel.PacienteID),
                                  nameof(PatientsModel.NombreCompleto));
        }

        public ActionResult Index()
        {
            return View(_roomsRegistersRepository.GetAll());
        }

        // GET: UniverstiyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UniverstiyController/Create
        public ActionResult Create()
        {
            ViewBag.Rooms = _roomsList;
            ViewBag.Patients = _patientsList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomsRegistrationsModel roomsRegistrationsModel)
        {
            try
            {
                _roomsRegistersRepository.AddRoomRegister(roomsRegistrationsModel);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Rooms = _roomsList;
                ViewBag.Patients = _patientsList;

                return View(roomsRegistrationsModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var room = _roomsRegistersRepository.GetById(id);

            _roomsList = new SelectList(_roomsRegistersRepository.GetAllRooms(),
                                        nameof(RoomsModel.HabitacionID),
                                        nameof(RoomsModel.NumeroHabitacion),
                                        room?.NumeroHabitacion?.HabitacionID);

            _patientsList = new SelectList(_roomsRegistersRepository.GetAllPatients(),
                                           nameof(PatientsModel.PacienteID),
                                           nameof(PatientsModel.NombreCompleto),
                                           room?.NombrePaciente?.PacienteID);

            ViewBag.Rooms = _roomsList;
            ViewBag.Patients = _patientsList;

            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoomsRegistrationsModel roomsRegistrationsModel)
        {
            try
            {
                _roomsRegistersRepository.EditRoomRegister(roomsRegistrationsModel);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Rooms = _roomsList;
                ViewBag.Patients = _patientsList;

                return View(roomsRegistrationsModel);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var room = _roomsRegistersRepository.GetById(id);

            if (room == null)
            {
                return NotFound();
            }

            var rooms = _roomsRegistersRepository.GetAllRooms();
            var pacient = _roomsRegistersRepository.GetAllPatients();

            room.NumeroHabitacion = rooms.FirstOrDefault(r => r.HabitacionID == room.HabitacionID);
            room.NombrePaciente = pacient.FirstOrDefault(p => p.PacienteID == room.PacienteID);

            return View(room);
        }

        // POST: UniverstiyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(RoomsRegistrationsModel roomsRegistrationsModel)
        {
            try
            {
                _roomsRegistersRepository.DeleteRoomRegister(roomsRegistrationsModel.RegistroHabitacionID);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(roomsRegistrationsModel);
            }
        }
    }
}

HospitalProjectDemo/HospitalProject/Views/RoomsRegister/Create.cshtml
@model HospitalProject.Models.RoomsRegistrationsModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>RoomsRegistrationsModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HabitacionID" class="control-label"></label>
                <select asp-for="HabitacionID"
                        asp-items="@ViewBag.Rooms"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="HabitacionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PacienteID" class="control-label"></label>
                <select asp-for="PacienteID"
                        asp-items="@ViewBag.Patients"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="PacienteID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProjectDemo/HospitalProject/Views/RoomsRegister/Delete.cshtml
@model HospitalProject.Models.RoomsRegistrationsModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RoomsRegistrationsModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistroHabitacionID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistroHabitacionID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HabitacionID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroHabitacion.NumeroHabitacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PacienteID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombrePaciente.NombreCompleto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input asp-for="RegistroHabitacionID" hidden class="form-control" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HospitalProjectDemo/HospitalProject/Views/RoomsRegister/Edit.cshtml
@model HospitalProject.Models.RoomsRegistrationsModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RoomsRegistrationsModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="RegistroHabitacionID" hidden class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="HabitacionID" class="control-label"></label>
                <select asp-for="HabitacionID"
                        asp-items="@ViewBag.Rooms"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="HabitacionID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PacienteID" class="control-label"></label>
                <select asp-for="PacienteID"
                        asp-items="@ViewBag.Patients"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="PacienteID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProjectDemo/HospitalProject/Views/RoomsRegister/Index.cshtml
@model IEnumerable<HospitalProject.Models.RoomsRegistrationsModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Nuevo Registro de habitacion</a>
</p>

@if (TempData["message"] != null)
{
    <div class="alert alert-primary" role="alert">
        @TempData["message"]
    </div>
}
<table class="table table-bordered table-striped table-responsive" id="roomsRegisterTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegistroHabitacionID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HabitacionID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PacienteID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegistroHabitacionID)
            </td>
            <td>
                @item.NumeroHabitacion?.NumeroHabitacion
            </td>
            <td>
                @item.NombrePaciente?.NombreCompleto
            </td>
            <td>
                    <a asp-controller="RoomsRegister" asp-action="Edit" asp-route-id="@item.RegistroHabitacionID" class="btn btn-primary">Editar</a>
                    <a asp-controller="RoomsRegister" asp-action="Delete" asp-route-id="@item.RegistroHabitacionID" class="btn btn-primary">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#roomsRegisterTable").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    }
                ],
                columnDefs: [
                    {
                        targets: 3,
                        orderable: false,
                        searchable: false
                    }
                ],
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/es-ES.json'
                }
            });
        });
    </script>
}