HospitalProjectDemo/HospitalProject/Controllers/DoctorController.cs
using HospitalProject.Models;
using HospitalProject.Repositories.Doctor;
using HospitalProject.Repositories.DoctorSpecialty;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Numerics;

namespace HospitalProject.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorRepository _doctorRepository;
        private SelectList _doctorSpecialtyList;

        public DoctorController(IDoctorRepository doctorRepository)
        {
            _doctorRepository = doctorRepository;

            _doctorSpecialtyList = new SelectList(_doctorRepository.GetAllSpecialty(), 
                                              nameof(DoctorSpecialtyModel.EspecialidadID), 
                                              nameof(DoctorSpecialtyModel.NombreEspecialidad));
        }

        public ActionResult Index()
        {
            return View(_doctorRepository.GetAll());
        }

        // GET: UniverstiyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UniverstiyController/Create
        public ActionResult Create()
        {
            ViewBag.DoctorSpecialty = _doctorSpecialtyList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DoctorsModel doctorsModel)
        {
            try
            {
                _doctorRepository.AddDoctor(doctorsModel);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.DoctorSpecialty = _doctorSpecialtyList;

                return View(doctorsModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var doctor = _doctorRepository.GetById(id);

            _doctorSpecialtyList = new SelectList(_doctorRepository.GetAllSpecialty(),
                                              nameof(DoctorSpecialtyModel.EspecialidadID),
                                              nameof(DoctorSpecialtyModel.NombreEspecialidad),
                                              doctor?.Especialidades?.EspecialidadID);

            ViewBag.DoctorSpecialty = _doctorSpecialtyList;

            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DoctorsModel doctorsModel)
        {
            try
            {
                _doctorRepository.EditDoctor(doctorsModel);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.DoctorSpecialty = _doctorSpecialtyList;

                return View(doctorsModel);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var doctor = _doctorRepository.GetById(id);

            if (doctor == null)
            {
                return NotFound();
            }

            var specialty = _doctorRepository.GetAllSpecialty();

            doctor.Especialidades = specialty.FirstOrDefault(r => r.EspecialidadID == doctor.EspecialidadID);

            return View(doctor);
        }

        // POST: UniverstiyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(DoctorsModel doctorsModel)
        {
            try
            {
                _doctorRepository.DeleteDoctor(doctorsModel.DoctorID);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(doctorsModel);
            }
        }
    }
}

HospitalProjectDemo/HospitalProject/Controllers/MedicinesController.cs
using HospitalProject.Models;
using HospitalProject.Repositories.DoctorSpecialty;
using HospitalProject.Repositories.Medicines;
using Microsoft.AspNetCore.Mvc;

namespace HospitalProject.Controllers
{
    public class MedicinesController : Controller
    {
        private readonly IMedicinesRepository _medicinesRepository;

        public MedicinesController(IMedicinesRepository medicinesRepository)
        {
            this._medicinesRepository = medicinesRepository;
        }

        public ActionResult Index()
        {
            return View(_medicinesRepository.GetAll());
        }

        // GET: UniverstiyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UniverstiyController/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MedicinesModel medicinesModel)
        {
            try
            {
                _medicinesRepository.AddMedicines(medicinesModel);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(medicinesModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var medicines = _medicinesRepository.GetById(id);

            if (medicines == null)
            {
                return NotFound();
            }

            return View(medicines);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MedicinesModel medicinesModel)
        {
            try
            {
                _medicinesRepository.EditMedicines(medicinesModel);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(medicinesModel);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var medicines = _medicinesRepository.GetById(id);

            if (medicines == null)
            {
                return NotFound();
            }

            return View(medicines);
        }

        // POST: UniverstiyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MedicinesModel medicinesModel)
        {
            try
            {
                _medicinesRepository.DeleteMedicines(medicinesModel.MedicamentoID);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(medicinesModel);
            }
        }
    }
}

HospitalProjectDemo/HospitalProject/Controllers/PatientController.cs
using HospitalProject.Models;
using HospitalProject.Repositories.DoctorSpecialty;
using HospitalProject.Repositories.Patients;
using Microsoft.AspNetCore.Mvc;

namespace HospitalProject.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientRepository _patientRepository;

        public PatientController(IPatientRepository patientRepository)
        {
            _patientRepository = patientRepository;
        }

        public ActionResult Index()
        {
            return View(_patientRepository.GetAll());
        }

        // GET: UniverstiyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UniverstiyController/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientsModel patientsModel)
        {
            try
            {
                _patientRepository.AddPatient(patientsModel);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(patientsModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var patient = _patientRepository.GetById(id);

            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PatientsModel patientsModel)
        {
            try
            {
                _patientRepository.EditPatient(patientsModel);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(patientsModel);
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var patient = _patientRepository.GetById(id);

            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: UniverstiyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(PatientsModel patientsModel)
        {
            try
            {
                _patientRepository.DeletePatient(patientsModel.PacienteID);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(patientsModel);
            }
        }
    }
}

HospitalProjectDemo/HospitalProject/Controllers/RoomController.cs
using HospitalProject.Models;
using HospitalProject.Repositories.DoctorSpecialty;
using HospitalProject.Repositories.Room;
using Microsoft.AspNetCore.Mvc;

namespace HospitalProject.Controllers
{
    public class RoomController : Controller
    {
        private readonly IRoomsRepository _roomsRepository;

        public RoomController(IRoomsRepository roomsRepository)
        {
            _roomsRepository = roomsRepository;
        }

        public ActionResult Index()
        {
            return View(_roomsRepository.GetAll());
        }

        // GET: UniverstiyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UniverstiyController/Create
        public ActionResult Create()
        {
            ViewBag.DoctorSpecialty = _roomsRepository;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomsModel roomsModel)
        {
            try
            {
                _roomsRepository.AddRoom(roomsModel);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.DoctorSpecialty = _roomsRepository;

                return View(roomsModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var rooms = _roomsRepository.GetById(id);

            if (rooms == null)
            {
                return NotFound();
            }

            return View(rooms);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoomsModel roomsModel)
        {
            try
            {
                _roomsRepository.EditRoom(roomsModel);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(roomsModel);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var rooms = _roomsRepository.GetById(id);

            if (rooms == null)
            {
                return NotFound();
            }

            return View(rooms);
        }

        // POST: UniverstiyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(RoomsModel roomsModel)
        {
            try
            {
                _roomsRepository.DeleteRoom(roomsModel.HabitacionID);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(roomsModel);
            }
        }
    }
}

HospitalProjectDemo/HospitalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalProject.styles.css" asp-append-version="true" />

    <link href="https://cdn.datatables.net/1.13.8/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DoctorSpecialty" asp-action="Index">Especialidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Habitaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Pacientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RoomsRegister" asp-action="Index">Registro Habitaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicines" asp-action="Index">Medicinas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultation" asp-action="Index">Consultas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HospitalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>